# Generated by Django 3.2.6 on 2021-08-26 03:00

import api.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(max_length=500, verbose_name='내용')),
                ('video_file', models.FileField(null=True, upload_to=api.models.get_file_path, verbose_name='영상 파일')),
                ('video_duration', models.IntegerField(null=True, verbose_name='영상 길이')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
