# Generated by Django 3.2.6 on 2021-08-29 08:33

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=500, verbose_name='글 원본 내용')),
                ('length', models.IntegerField(default=0, verbose_name='글 원본 길이')),
                ('processed_content', models.TextField(default='', max_length=500, verbose_name='글 욕설 처리된 내용')),
                ('is_processed', models.BooleanField(default=False, verbose_name='글 욕설 처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='글 생성 일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글 소유자')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='제목')),
                ('album', models.CharField(default='', max_length=100, verbose_name='분류')),
                ('composer', models.CharField(default='', max_length=100, verbose_name='제목')),
                ('copyright', models.TextField(default='', max_length=500, verbose_name='저작권')),
                ('file', models.FileField(null=True, upload_to=api.models.get_file_path, verbose_name='파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
