# Generated by Django 3.2.6 on 2021-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='composer',
            field=models.CharField(default='', max_length=100, verbose_name='저자'),
        ),
    ]
