# Generated by Django 3.0.8 on 2020-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deep',
            name='processed_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
