# Generated by Django 3.0.8 on 2020-10-28 06:39

import deep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0004_auto_20201028_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=deep.models.get_processed_path, verbose_name='처리된파일'),
        ),
    ]
