# Generated by Django 3.0.8 on 2020-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0008_auto_20201029_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='deep',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='내용'),
        ),
    ]
