# Generated by Django 3.0.8 on 2020-10-31 17:02

import deep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0009_deep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deep',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='영상 길이'),
        ),
        migrations.AlterField(
            model_name='deep',
            name='video_file',
            field=models.FileField(null=True, upload_to=deep.models.get_file_path, verbose_name='영상'),
        ),
    ]
