# Generated by Django 3.0.8 on 2020-10-28 06:27

import deep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0003_auto_20201028_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='처리된파일'),
        ),
        migrations.AlterField(
            model_name='deep',
            name='video_file',
            field=models.FileField(null=True, upload_to=deep.models.get_file_path, verbose_name='파일'),
        ),
    ]
