# Generated by Django 3.0.8 on 2020-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0006_auto_20201028_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deep',
            name='processed_file',
        ),
        migrations.AlterField(
            model_name='deep',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='제목'),
        ),
    ]
