# Generated by Django 3.0.8 on 2020-10-29 14:35

import deep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0007_auto_20201028_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='video_file',
            field=models.FileField(null=True, upload_to=deep.models.get_file_path, verbose_name='파일'),
        ),
    ]
