# Generated by Django 3.0.8 on 2020-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0010_auto_20201101_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='video_duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='영상 길이'),
        ),
    ]
