# Generated by Django 3.0.8 on 2020-10-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0011_auto_20201101_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일자'),
        ),
    ]
