# Generated by Django 3.0.8 on 2020-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0012_auto_20201101_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='deep',
            name='choice_method',
            field=models.CharField(max_length=50, null=True, verbose_name='영상 처리 방식'),
        ),
    ]
